### PR TITLE
Update CI

### PR DESCRIPTION
**Pull request by benbovy**
- [x] add azure pipelines config for Windows and MacOS (shamelessly copied from https://github.com/xtensor-stack/xtensor)
- [x] remove travis CI config
- [x] add python bindings builds/tests
- [x] update README badges

### CODE REVIEW

**Comment by benbovy** [comment]
@adriendelsalle do you have any idea on why the azure pipeline is failing on Windows? I see a lot of warnings but no apparent compilation error, and still the ninja build fails...

**Comment by adriendelsalle** [comment]
Hi @benbovy !
There are errors but generated by `gtest`. Could you please merge #65 and rebase?
I made a fix for a similar (but not identical) problem with msvc this morning and I would like to check if it helps.

If not I will try to reproduce locally!

**Comment by adriendelsalle** [comment]
Looks like it still breaks. I will have a look

**Comment by benbovy** [comment]
@adriendelsalle in the last commit I removed the `test_fastscapelib` target and instead use `cmake --build . -- test` to run all the tests. It saves some compilation time when building all test targets, and the output is a bit more compact.

Let me know if you have any objection/thoughts, I can add it back if that's useful.

**Comment by benbovy** [comment]
> I made a fix for a similar (but not identical) problem with msvc this morning and I would like to check if it helps.

Updating the git tag of downloaded gtest fixed it.

**Comment by adriendelsalle** [comment]
Hi @benbovy 

No it's ok for me to either build the full one or the smaller targets one by one.
Splitting the targets was done for developping faster :).

**Pull request merged**
