### PR TITLE
Flow graph API

### PR DESCRIPTION
**Pull request by adriendelsalle**
This PR aims to add a `flow_graph` API. It is broadly inspired by the [design notes](https://github.com/fastscape-lem/fastscapelib/wiki/Design-notes:-flow-routing) of this repo.
It includes all possible methods considered as `flow_router`s and `sink_resolver`s.

@benbovy Could you please provide an example `flow_graph` (e.g. pointers to routers and resolvers methods already implemented in this repo even if they are not compatible with the `grid` structure)? I would like to set up a fully representative test case. 
Are those two classes limited in term of virtual methods to:
- `flow_graph`: `route_impl`
- `sink_resolver`: `resolve_before_route` and `resolve_after_route`

Thanks!

### CODE REVIEW

**Comment by benbovy** [comment]
Great! I'm happy to provide more details here. Note: this is all still open to discussion, some design choices might still not be the best. 

## `flow_graph` "core" data members

The following data members are updated when calling `flow_graph::update()`, which (re)builds the graph from a given elevation field.

- `m_elevation`: the elevation field passed to `flow_graph::update()`.
  - `flow_router` subclasses should have read-only access, and `sink_resolver` subclasses should have read-write access.  
  - A copy may be needed if `sink_resolver` changes the topography (e.g., fill closed depressions). `flow_graph::update()` should never update in place the original elevation array! Otherwise, a view is better.

- Internal data structures for representing the graph.
  - The best data structures will depend on the specific method implemented in the `flow_router` subclass instance given to the `flow_graph` constructor. Adjacency lists are better suited for the methods currently implemented in `flow_routing.hpp`, but if we want to implement a matrix-based approach then adjacency matrices will be more appropriate.
  - although `flow_graph` represents a directed graph, we often need to traverse it in both directions, i.e., from sources (ridges) to sinks (outlets) or from sinks to sources. In the case of adjacency lists, for better performance it might be good to store two vectors of vectors, one for each directions (flow receivers vs. flow donors).
  - Flow routers can be either single or multiple flow directions (i.e., convergent vs. divergent flow). In the case of single flow directions, the graph reduces to a tree and the adjacency lists in the sources->sinks direction may be simplified (e.g., using a simple vector instead of a vector of vectors). 
  - As we often need to traverse the flow graph many times, we would need to pre-compute and/or cache the node ordering (either BFS or DFS). See, e.g., `compute_stack` in `flow_routing.hpp`. Again here, the exact data structure for the cache might depend on the implementation in `flow_router` subclasses (for example, a parallel computation of flow routing may be based on some kind of graph partitioning). 
  - Both `flow_router` and `sink_resolver` subclasses need read/write access to these internal data structures.

For convenience, I would be nice to publicly expose the data members listed here above (read-only). As we may want to access it from C++ but also from the bindings (Python/Numpy), we would probably need to expose graph data through a static array interface, e.g., in the case of adjacency lists:

- `elevation()`: the actual elevation values used for computing the graph, either as a `xt::view` or `xt_container_t` if a copy is used
- `nb_receivers()`: returns the number of flow receivers for each grid node as `xt::xtensor<std::uint8_t, 1>` (optional, not very useful if single flow direction is used)
- `receivers()`: returns flow receivers grid node indexes, either as `xt::xtensor<size_type, 1>` or `xt::xtensor<size_type, 2>` where the 2nd dimension has a known size equal to grid `max_neighbors`.
- `weights()`: returns the flow partition ratio for each receiver (optional, not very useful if single flow direction is used)
- `nb_donors()`: like `nb_receivers()` but for flow donors (not optional here)
- `donors()`: like `receivers()` but for flow donors
- `bfs_order()` or `dfs_order()`: returns the pre-sorted node indexes for fast graph traversal, e.g., as `xt::xtensor<size_type, 1>` (the equivalent of `stack` in `flow_routing.hpp`).

## `flow_graph` "derived" data members

Some extra variables like drainage basin ids, pit nodes, etc. can be directly derived from the flow graph and are very useful for a variety of purposes. See, e.g., `compute_basins` and `find_pits` in `flow_routing.hpp`. Since these are common and quite cheap to compute, we could include it in the `flow_graph` class. But we can address this later.

## `flow_router` examples

The most basic example would be a `single_flow_router` subclass, in which we can encapsulate the functions `compute_receiver`, `compute_donors` and `compute_stack` (implemented in `flow_routing.hpp`), and call them in `route_impl`.

Here below are two other, interesting and more advanced examples:

- parallel implementation of fastscape's current algorithms: [paper](https://arxiv.org/pdf/1803.02977.pdf) and [code](https://github.com/r-barnes/Barnes2019-Landscape).
- matrix-based implementation of flow routing / drainage area: [paper1](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2013WR014326) and [paper2](https://gmd.copernicus.org/articles/12/4165/2019/).

## `sink_resolver` examples

The most basic example is to not use any sink resolver :-).

Another, simple example would be a `pflood_sink_resolver` subclass, in which we would call `fill_sinks_sloped` with `flow_graph.m_elevation` in `resolve_before_route`. `fill_sinks_sloped` is implemented in `sinks.hpp` and I'd like to refactor it to make it grid-agnostic.

A more advanced example is in #41 ([paper](https://esurf.copernicus.org/articles/7/549/2019/)).

**Comment by benbovy** [comment]
> The best data structures will depend on the specific method implemented in the flow_router subclass instance given to the flow_graph constructor.

> Again here, the exact data structure for the cache might depend on the implementation in flow_router subclasses (for example, a parallel computation of flow routing may be based on some kind of graph partitioning).

Thinking more about this, I'm wondering if the internal data structures used to represent the graph shouldn't belong to the `flow_router` subclasses instead of `flow_graph`? That would probably make more sense, since it might differ quite much depending on the flow routing implementation.

Similarly to the grid API (node neighbors), we could also extend the API of `flow_graph` so that we can iterate over the flow receivers (or donors) of a given grid node. If the implementation differs from one flow routing method to another, we would need to extend the API of `flow_router` too...

... Then what's the point of having a `flow_graph` class that is distinct of `flow_router`, if the former just consists of methods that call methods of `flow_router` instances? That's an open question..

**Comment by adriendelsalle** [comment]
Thanks @benbovy from your answers! I will digest this during this first implementation of the API :)

**Comment by benbovy** [comment]
> Another, simple example would be a pflood_sink_resolver subclass, in which we would call fill_sinks_sloped

`fill_sinks_sloped` will compatible with the new grid system after #70.

**Comment by adriendelsalle** [comment]
Hi @benbovy !
It's almost finished. I still have ICE in CI on VS2015, do you prefer either dropping testing this conf or split tests in smaller files to avoid to many templates instantiation (causing the ICE) ?

Thanks!

**Comment by benbovy** [comment]
I still have ICE in CI on VS2015, do you prefer either dropping testing this conf or split tests in smaller files to avoid to many templates instantiation (causing the ICE) ?

I think we can drop the VS2015 configuration. I'd like to add python build and tests for all platforms with azure (and maybe remove appveyor) in #64.

**Review by benbovy — COMMENTED** [review]
Big thanks @adriendelsalle for this epic PR!!

I've left a few minor comments / questions in inline comments.

I think it will take me more time to digest all of this, but this shouldn't block you/us. Maybe except some minor details to address, we should merge this as-is.

Looking at the implementation in this PR, I have two bigger concerns that we can discuss later, after merging this:

- Which data-structures should we use for handling the graph (i.e., receivers, donors, etc.) internally in `flow_graph`, `flow_router` and `sink_resolver` classes? E.g., vectors of vectors (dynamic) or xtensor containers?
  -  `flow_graph` public methods like `receivers()`, `donors()`, etc. are meant to be called very occasionally. Instead of simply returning the underlying members, they could coerce (maybe with copy?) the graph internal structures into xt::xtensor objects (static arrays). 
- Where the flow graph internal data-structures should belong? If the choice of optimal structures depends on the flow routing method (e.g., matrix-based approach vs. explicit loops on linked lists), it would make sense to rather define those as members of `flow_router` subclasses, and require the later to provide some API to convert those structures into the structures exposed in the `flow_graph` API. One issue would then be how to access those structure from sink resolver classes.

**Pull request merged**
