### PR TITLE
Add grid classes

### PR DESCRIPTION
**Pull request by benbovy**
Grid classes hold information about grid geometry, topology and node status
(boundary conditions) and implement some iterators over node neighbors exposed
by a common API.

Two kinds of grid are added:

- Profile grid (1D uniform)
- Raster grid (2D rectangular uniform)

### CODE REVIEW

**Comment by benbovy** [comment]
Thanks for the tip @gcordonn! Let's try...

Otherwise, I don't think we're gonna blow the memory by making this tiny array non-static.

**Comment by benbovy** [comment]
On another topic, I'm currently thinking on what would be an efficient while convenient approach to return the list of neighbors at a given node index.

- For unstructured meshes (possibly later supported in this library), there is not much to think IMO since the grid topology must be defined explicitly.
- For 1D structured grids, I currently pre-compute and store all neighbors at grid initialization. The extra memory it takes is not a big deal.
- For 2D raster grids, however, it would be silly to pre-compute and store all neighbors of all nodes. Instead, we could generate the list of neighbors on the fly, still with some optimization (e.g., by pre-computing the index offsets + distances for each of the 9 possible locations of the nodes on the grid - inner + 4 corners + 4 borders -, taking into account any looped boundaries at those locations).

The problem is which container to choose for the list of neighbors. All inner nodes have 8 (or 4) neighbors, while border and corner nodes may have less neighbors. I see three options:

1. Use ``std::vector`` to encompass all cases. I'm wondering if the overhead of allocation on the heap is significant or not in this case, considering that those kinds of vectors will be created a lot in inner loops.

2. Use ``std::array`` with the max nb. of neighbors, and also return the number of neighbors. This option is not very nice from a API point-of-view, as simply using range based loops like ``for(const auto& nn : grid.neighbors())`` is not possible.

3. Use ``std::array`` and add some kind of flag in each element saying if an it is a valid node or not. This would require some ``if`` statements to test if the node is valid, so this is not very nice either.

Any idea on this?

**Comment by gcordonn** [comment]
What about an iterator?

Another issue with raster grids is the optimisation of the traitment of the bounds. In classical un-optimized code, we parse all neighbors, and for each of them we check if it is inbound. This is 4 comparisons times the number of neighbors, useless for the huge majority of the nodes. Slightly more optimized is to parse from min(0, x-1) to max(ncols-1, x+1), 2 comparisons per dimension but still unneded for all the inner nodes. A better solution is to separate the treatment of inner nodes from boundary nodes.

**Comment by benbovy** [comment]
> What about an iterator?

Could you provide a snippet?

> A better solution is to separate the treatment of inner nodes from boundary nodes.

Yes this is indeed a good usual way to proceed, although this requires to parse inner / boundary nodes separately *each time*, and possibly duplicate the processing code or write lambda... 

Actually, I like [this suggestion](https://stackoverflow.com/a/32504021) of pre-computing an array of 9-codes corresponding to the 9 specific locations on the grid, and also pre-computing the offsets / distances for those 9 locations, taking looped boundary conditions into account (which must be uniform and consistent on the grid borders). Retrieving the neighbors of a node would then just consist in getting the stored offsets / distances that correspond to the code of the node ; there is no in/out grid testing.

**Comment by gcordonn** [comment]
Leaving aside many "clean" c++ considerations:

```c++
class Grid {

    public:

    struct NeighborRange {
        
        struct iterator {
            int& operator * () {
                return nb;
            }
            iterator& operator ++ () {
                ++nb;
                return *this;
            }
        
            bool operator != (const iterator& other)
            {
                return nb != other.nb;
            }
        
            int nb;
        };
        
        iterator begin()
        {
            return iterator {0};
        };
        
        iterator end()
        {
            return iterator{4};
        }
        
    };
    
    NeighborRange getNbs()
    {
        return NeighborRange();
    }
};

int main()
{
    Grid g;
    
    for (auto& nb : g.getNbs())
    {
        std::cout << nb << std::endl;
    }
}
```

And I also like this suggestion. Only issue: you have to store a char array of the same size as the grid. But it may be worth it.

**Comment by gcordonn** [comment]
Same code but for the previously mentioned suggestion:

```c++
#include <iostream>
#include <array>

class Grid {

    public:
    
    static inline constexpr std::array<ptrdiff_t, 6> nb_array {-10, -1, 1, 10, // inner
                                                               -10,1}; // corner
    
    using const_iterator = std::array<ptrdiff_t, 6>::const_iterator;
    static inline constexpr  std::array<const_iterator, 3> it_list {nb_array.begin(), nb_array.begin()+4, nb_array.end()};

    struct NeighborRange {
    
        NeighborRange(char code) : code{code} {}
        char code;
    
        const_iterator begin()
        {
            return it_list[code];
        };
        
        const_iterator end()
        {
            return it_list[code+1];
        }
        
    };
    
    NeighborRange getNbs(char code)
    {
        return NeighborRange(code);
    }
    
    
    
};

int main()
{
    Grid g;
    
    for (const auto nb : g.getNbs(0))
    {
        std::cout << nb << std::endl;
    }
}
```

**Comment by benbovy** [comment]
Thanks for the snippet! Very useful as I'm not yet familiar with C++ iterators.

> Only issue: you have to store a char array of the same size as the grid. 

If that's an issue, we could still implement a better storage/computation tradeoff, e.g., using two 1-d arrays to pre-store the rows and cols components of the code expression, as suggested by the author of the SO comment (I haven't checked yet the code expression, though).

**Comment by benbovy** [comment]
> we could still implement a better storage/computation tradeoff, e.g., using two 1-d arrays to pre-store the rows and cols components of the code expression

```cpp
std::array<std::size_t, 2> shape = {10, 20};

std::vector<int> make_gcode_dim(std::size_t dim)
{
    int fill_value = dim * 2 + 1; 
    
    std::vector<int> gcode_vec(shape[dim], fill_value);
    
    gcode_vec[0] = 0;
    gcode_vec[shape[dim]-1] = fill_value * 2;
    
    return gcode_vec;
}

auto gcode_row = make_gcode_dim(0);
auto gcode_col = make_gcode_dim(1);

int get_gcode(int r, int c)
{
    return gcode_row[r] + gcode_col[c];
}

std::cout << get_gcode(0, 0);   // 0 - top-left corner
std::cout << get_gcode(1, 0);   // 1 - left border
std::cout << get_gcode(9, 0);   // 2 - bottom-left corner
std::cout << get_gcode(0, 1);   // 3 - top border
std::cout << get_gcode(1, 1);   // 4 - inner
std::cout << get_gcode(9, 1);   // 5 - bottom border
std::cout << get_gcode(0, 19);  // 6 - top-right corner
std::cout << get_gcode(1, 19);  // 7 - right border
std::cout << get_gcode(9, 19);  // 8 - bottom-right corner
```

**Comment by gcordonn** [comment]
Why not ! but then there is an extra check for boundary conditions. There is a choice here: if we allow for inner boundary conditions, then it can be combined with the extra 2d array for free. Otherwise the two 1D arrays are the way to go !

The bast, of course, would be that all is generic enough to be able to handle both implmenentations.

**Comment by benbovy** [comment]
Note: here we just want to solve the problem of grid connectivity (including grid boundaries), which is different from boundary conditions (i.e., fixed value / fixed gradient). The latter shouldn't be handled by grid classes, which just hold this information that may be used (or ignored) elsewhere.

For example, for diffusion ADI, fixed value conditions are always assumed on grid borders (also any "boundary" condition set for inner nodes are ignored) regardless of the actual boundary conditions set in the grid object, simply because the algorithm doesn't currently supports other configurations.

The only exception is looped boundaries, as it affects grid connectivity. But we could avoid any check by a proper pre-computation of the offsets.

**Comment by benbovy** [comment]
Actually, in the current implementation of diffusion ADI it would be tricky to support looped boundaries too, so boundary conditions are likely to be totally ignored for now for this feature. This implementation of diffusion is vectorized and only valid for raster grids. We could provide an alternative implementation of other kinds of grids, but this is another issue.

**Comment by benbovy** [comment]
FWIW I've just noticed that xtensor 0.20 adds support for periodic indices.

**Comment by gcordonn** [comment]
Are you sure you want to go this far for gcc<5 support? Modern C++ featuresallos to read more readable, safe and efficient code. Here, going from `unordered_map` to `map`might, in some cases, result in performance drop.

I would rather recomand using the full c++14 features and request a compliant compiler as a dependency.

**Comment by benbovy** [comment]
Until recently conda-forge still used gcc < 5 for building the packages in its channel, but now that the compiler migration is done this is less important.

In this specific case (a ``map`` with just a few values) it's not a big deal, but this is not the first time that I waste some time trying to fix compilation issues for old versions of gcc, so I'd be happy to drop support for it for sure!

However, I don't have a clear idea yet about of the usual environments within which potential users would compile the library (e.g., HPC, old debian distros, etc.), and I'd like to promote the library for its portability...

**Comment by benbovy** [comment]
I've been thinking a bit on what would be the best approach (API) to loop over neighbor nodes.

Currently, the idea is a grid method ``neighbors()``, which returns an iterator of ``neighbor_node`` structures. The latter embed grid indices, node status and distance. A typical use-case is:

```cpp
for (size_t row=0; row < grid.shape[0], ++row)
{
    for (size_t col=0; col < grid.shape[1], ++col)
    {
        auto min_slope = std::numeric_limits<double>::max();
        for (const auto& nb : grid.neighbors(row, col))
        {
            auto slope = (elevation(nb.row, nb.col) - elevation(row, col)) / nb.distance;
            if (slope < min_slope) { min_slope = slope; }
        }
    }
}
```

The problem is that creating ``neighbor_node`` structures might not be the most efficient approach, especially considering that we don't always need ``distance`` or ``status`` when visiting the neighbors.

I'm wondering if a better way wouldn't be a grid method that return an iterator with the values of a given scalar field (like elevation) at the neighbor nodes, i.e., ``grid.values_at_neighbors(X scalar_field, size_t row, size_t col)``. If ``field`` is a xtensor object, we could even return an index view, e.g., ``grid.neighbors_view(X scalar_field, size_t row, size_t col)``.

Status at neighbor nodes would be returned using the same method, and node indices / distances to neighbor nodes would be returned by separate methods:

```cpp
template <class X, class V>
auto grid.neighbors_view(const X& scalar_field, size_t row, size_t col) -> V;

IndexRange grid.neighbors_indices(size_t row, size_t col);

DistanceRange grid.dist_to_neighbors(size_t row, size_t col);
```

My feeling is that this approach might lead to more elegant/vectorized code, using STL algorithms and/or xtensor functions instead of manual loops over the neighbors like shown in the example above.

Opinions @gcordonn ?

**Comment by gcordonn** [comment]
The example above is already quite compatible with stl. Anyway, both code do not seem very different, but we just need an operator that given a node id, returns the distance. it is quite often that we want to access the different attributes (distance, status, ...) and know the node id at the same time. 

Why not another alternative, where a function returns the different elements based on a iterator. If you look at  the proposals for the upcoming c++ range library, there is some kind of pipe operator on the iterators:

something like:

```c++
auto dists = grid.distances  | grid.neighbors(r,c);
```

**Comment by benbovy** [comment]
I added some benchmarks to compare different ways of getting the list of (row, col) indices of the neighbors of a raster grid node. It turns out using nested xtensors (i.e., ``xt::xtensor<xt::xtensor_fixed<size_type, xt::xshape<2>>, 1>``) is very slow.

Results from getting neighbor indices using loops and separate offset arrays for row and col (i.e., the "classical approach"):

```
bm_raster_grid_neighbor_classic<fs::raster_connect::queen>/256             0 ms          0 ms       1991
bm_raster_grid_neighbor_classic<fs::raster_connect::queen>/512             1 ms          1 ms        502
bm_raster_grid_neighbor_classic<fs::raster_connect::queen>/1024            6 ms          5 ms        124
bm_raster_grid_neighbor_classic<fs::raster_connect::queen>/2048           22 ms         22 ms         32
bm_raster_grid_neighbor_classic<fs::raster_connect::queen>/4096           88 ms         87 ms          8
```

Results from getting the indices using nested xtensors:

```
bm_raster_grid_neighbor_indices<fs::raster_connect::queen>/256            19 ms         19 ms         35
bm_raster_grid_neighbor_indices<fs::raster_connect::queen>/512            79 ms         78 ms          9
bm_raster_grid_neighbor_indices<fs::raster_connect::queen>/1024          313 ms        309 ms          2
bm_raster_grid_neighbor_indices<fs::raster_connect::queen>/2048         1212 ms       1198 ms          1
bm_raster_grid_neighbor_indices<fs::raster_connect::queen>/4096         4909 ms       4854 ms          1
```

The two results are not directly comparable, but still...

**Comment by adriendelsalle** [comment]
Hi @benbovy !

Running the benchmark today gives me almost the same results for the `classic` method but 4-5x faster for the `indices` one:
``` bash
bm_raster_grid_neighbor_view<fs::raster_connect::queen>/256                5 ms          5 ms        149
bm_raster_grid_neighbor_view<fs::raster_connect::queen>/512               19 ms         19 ms         37
bm_raster_grid_neighbor_view<fs::raster_connect::queen>/1024              75 ms         75 ms          8
bm_raster_grid_neighbor_view<fs::raster_connect::queen>/2048             298 ms        298 ms          2
bm_raster_grid_neighbor_view<fs::raster_connect::queen>/4096            1198 ms       1198 ms          1
```
Do you have a reference implementation in FORTRAN that already do exactly this kind of computation for both the internal logic of it but also to have a performance reference? Is it the `classic` one ? How do you handle the periodic conditions then?

Thanks!

**Comment by benbovy** [comment]
> Running the benchmark today gives me almost the same results for the classic method but 5-6x faster for the indices one

That's a nice speedup! But it's still an order of magnitude slower than the classic method, so I think the current `indices` approach in this PR is still not the right one.

> Do you have a reference implementation in FORTRAN that already do exactly this kind of computation for both the internal logic of it but also to have a performance reference? Is it the classic one ? How do you handle the periodic conditions then?

Yes, there is an example here: https://github.com/fastscape-lem/fastscapelib-fortran/blob/18f25888b16bf4cf23b00e79840bebed8b72d303/src/FlowRouting.f90#L302-L362

It's a specific case for finding the node receivers (edge targets) while building a flow graph on top of the raster grid. periodic-conditions are handled with no "grid-agnostic" level of abstraction (i.e., raw `if` statements).

Unfortunately, we don't have "micro"-benchmarks for this Fortran library, although if needed it should be pretty fast to write one for this use case.

**Comment by adriendelsalle** [comment]
Thanks for the pointer! I will have a look at it!

There is a bias in the benchs, the classic method in not storing neighbors indices as it's done for the new `indices` implementation.

A new speedup has been achieved in #53 by explicitly dropping aliasing in `xtensor` and the 2 methods have the same efficiency.

We definitely want to keep focused on performance! If you have some guess of the Fortran code one, it would somehow help to know if we are on the right path.
Maybe a simple `timeit` using the python bindings would be enough for an heavy operation (the overhead will be many orders of magnitude lower).

**Comment by benbovy** [comment]
Closing this as it has been implemented in #51, #53, #54, #57, #60, #62.

**Pull request closed without merging**
